# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-24 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170824_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='base',
            new_name='name',
        ),
    ]
